[2024-04-02T08:59:51.282+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-04-02T08:59:46.525398+00:00 [queued]>
[2024-04-02T08:59:51.289+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-04-02T08:59:46.525398+00:00 [queued]>
[2024-04-02T08:59:51.290+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-04-02T08:59:51.393+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-04-02 08:59:46.525398+00:00
[2024-04-02T08:59:51.397+0000] {standard_task_runner.py:57} INFO - Started process 13851 to run task
[2024-04-02T08:59:51.399+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2024-04-02T08:59:46.525398+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpaypijtr6']
[2024-04-02T08:59:51.400+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask extract_task
[2024-04-02T08:59:51.461+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2024-04-02T08:59:46.525398+00:00 [running]> on host codespaces-e864db
[2024-04-02T08:59:51.563+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T08:59:46.525398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-02T08:59:46.525398+00:00'
[2024-04-02T08:59:51.564+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-02T08:59:51.565+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://r2.datahub.io/clt989dvv0003l708h2jgh5ef/main/raw/data/constituents.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/manual/manual-extract-data.csv']
[2024-04-02T08:59:51.573+0000] {subprocess.py:86} INFO - Output:
[2024-04-02T08:59:51.578+0000] {subprocess.py:93} INFO - --2024-04-02 08:59:51--  https://r2.datahub.io/clt989dvv0003l708h2jgh5ef/main/raw/data/constituents.csv
[2024-04-02T08:59:51.593+0000] {subprocess.py:93} INFO - Resolving r2.datahub.io (r2.datahub.io)... 104.21.40.221, 172.67.157.38, 2606:4700:3030::ac43:9d26, ...
[2024-04-02T08:59:51.596+0000] {subprocess.py:93} INFO - Connecting to r2.datahub.io (r2.datahub.io)|104.21.40.221|:443... connected.
[2024-04-02T08:59:51.727+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 416 Range Not Satisfiable
[2024-04-02T08:59:51.727+0000] {subprocess.py:93} INFO - 
[2024-04-02T08:59:51.727+0000] {subprocess.py:93} INFO -     The file is already fully retrieved; nothing to do.
[2024-04-02T08:59:51.728+0000] {subprocess.py:93} INFO - 
[2024-04-02T08:59:51.728+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-02T08:59:51.766+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=challenge_dag, task_id=extract_task, execution_date=20240402T085946, start_date=20240402T085951, end_date=20240402T085951
[2024-04-02T08:59:51.812+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-04-02T08:59:51.828+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
